spring:
  datasource:
    driverClassName: org.h2.Driver
    password:
    url: jdbc:h2:mem:testdb
    username: sa
  environment:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  jpa:
    properties:
      ddl-auto: create
      dialect: org.hibernate.dialect.H2Dialect
      hibernate:
        format_sql: true
    open-in-viwer: true
    show-sql: false